app_add_friend/urls.py
from django.conf.urls import url
from .views import index, Add_New_Friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^Add_New_Friend', Add_New_Friend, name='Add_New_Friend'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index, profile, delete
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', index, name='index'),
	#url(r'^$', RedirectView.as_view(url='/profile/1234/', permanent=False), name='index'),
	url(r'^delete$', delete, name='delete'),
	url(r'^(\w+)?$', profile, name='profile')
]

app_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_status/urls.py
from django.conf.urls import url
from .views import index, update_status, show_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^update_status', update_status, name='update_status'),
    url(r'^show_post', show_post, name='show_post'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_stats.urls as home
import app_add_friend.urls as app_add_friend
import app_status.urls as app_status
import app_profile.urls as app_profile
from app_stats.views import index as index_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stats/', include(home, namespace='home')),
    url(r'^add-friend/', include(app_add_friend, namespace='app-add-friend')),
    url(r'^status/', include(app_status, namespace='app-status')),
    url(r'^profile/', include(app_profile, namespace='profile')),
    url(r'^$', index_stats, name='index'),
]

app_add_friend/models.py
from django.db import models

# Create your models here.
class Add_Friend(models.Model):
    name = models.CharField(max_length=25)
    url = models.URLField(default='',max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Profile(models.Model):
	id = models.CharField(max_length=10, primary_key=True)
	
	name = models.CharField(max_length=25)
	birthday = models.DateField()
	gender = models.CharField(max_length=6)
	expertise = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	email = models.EmailField(max_length=50)
	
	def __str__(self):
		return '('+self.id+':'+self.name+')'

pro = Profile(id='5678',name='Naufal is ok I guess',birthday=datetime(1100,5,7),gender='Male',expertise='Being fat',description='lorem ipsum',email='Naufal@nyahoo.cum')
pro.save()

app_stats/models.py
from django.db import models

# Create your models here.

app_status/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

app_add_friend/forms.py
from django import forms

# Create your forms here.
class Add_Friend_Form(forms.Form):
    error_message = {
        'required': 'Please fill out this field'
        }
    attrs = {
        'class': 'form-control'
        }
           
    name = forms.CharField(label='Name', required=True, max_length=25, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=attrs))

app_status/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Please fill the input here',
    }
    attrs = {
        'class': 'form-control',
        'cols': 8,
        'rows': 4,
    }

    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

app_add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
from .models import Add_Friend

# Create your views here.
response = {}
def index(request):
    response['author'] = "Muhammad Wildan Aziz"
    add_friend = Add_Friend.objects.all()
    response['add_friend'] = add_friend
    html = 'add_friend/add_friend.html'
    response['add_friend_form'] = Add_Friend_Form
    return render(request, html, response)

def Add_New_Friend (request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        add_friend = Add_Friend(name=response['name'],url=response['url'])
        add_friend.save()
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Profile
from .models import pro

# from ..app_profile.models import Profile

response = {}
# Create your views here.
def index(request): # Temporary, to allow testcase to succeed
	response['name'] = pro.name
	response['birthday'] = pro.birthday
	response['gender'] = pro.gender
	response['expertise'] = pro.expertise
	response['description'] = pro.description
	response['email'] = pro.email
	return render(request, 'profile.html', response)
	
def delete(request):
	Profile.objects.all().delete()
	print(Profile.objects.all())
	return render(request, 'profile.html')
	
def profile(request, profile_id=pro.id):
	prof = Profile.objects.get(id=profile_id)

	dictio = {
		'id' : id,
		'name' : prof.name,
		'birthday' : prof.birthday,
		'gender' : prof.gender,
		'expertise' : prof.expertise,
		'description' : prof.description,
		'email' : prof.email,
	}
	return render(request, 'profile.html', dictio)

app_stats/views.py
from django.shortcuts import render
from app_profile.models import pro
from app_status.models import Message
from app_add_friend.models import Add_Friend

# Create your views here.
response = {}
def index(request):
    try:
        latest_status = Message.objects.latest('created_date')
    except Message.DoesNotExist:
        latest_status = None
        
    response['name'] = pro.name
    response['latest'] = latest_status
    response['number_of_posts'] = Message.objects.all().count()
    response['number_of_friends'] = Add_Friend.objects.all().count()
    return render(request, 'app_stats/stats.html', response)

app_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Create your views here.

response = {'author': "Para Pengabdi Beskem"}

def index(request):
    html = 'app_status/status.html'
    response['message_form'] = Message_Form
    message = Message.objects.all()
    response['message'] = message
    return render(request, html, response)

def update_status(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        message = Message(message=response['message'])
        message.save()
        html = 'app_status/status.html'
        return HttpResponseRedirect('/status/')
    else:        
        return HttpResponseRedirect('/status/')

def show_post(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'app_status/status.html'
    return render(request, html , response)

app_add_friend/templates/add_friend/add_friend.html
{% extends "app_stats/layout/base.html" %}
{% block content %}

<h2 style="margin-top:-20px;">Add Friend</h2>
<hr/>
<section name="add-friend-list" id = "add-friend-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app-add-friend:Add_New_Friend' %}">
            {% csrf_token %}
            {% for field in add_friend_form %}
            {{ field.label_tag }}
            <p>{{ field }}</p>
            {% endfor %}
            <br> 
            <input style="margin-left:1000px" class="btn1 btn-lg btn-info" id="submit" type="submit" value="Add Friend" >
        </form>
    </div>

<h2 style="margin-top:-20px;">List Friend</h2>
<table class="table">
    <thead>
        <th>Names</th>
        <th>URL</th>
        <th>Dates</th>
    </thead>
    <tbody>
        {% for i in add_friend reversed %}
        <td> {{i.name}} </td>
        <td> <a href="{{i.url}}" > {{i.url}} </a></td>
        <td> {{i.created_date}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app_profile/templates/profile.html
{% extends "app_stats/layout/base.html" %}

{% block content %}
<h2 Style="margin-top:-20px;">Profile</h2>
<hr/>
<div id="ember2844" class="Elevation-2dp profile-background-image profile-background-image--loading ember-view">
</div>
<div id="ember2853" class="ember-view">
    <section id="ember2858" class="pv-profile-section pv-top-card-section artdeco-container-card ember-view">
        <div class="pv-top-card-section__profile-photo-container">
            <div class="pv-top-card-section__photo-wrapper EntityPhoto-circle-8">
                <label for="member-photo-edit-upload-input" class="visually-hidden">
                    "Profile photo"
                </label>
                <div class="pv-top-card-section__edit-photo profile-photo-edit ember-view">
                    <button data-control-name="edit_profile_photo" class="profile-photo-edit__edit-btn" data-ember-action data-ember-action-2888="2888">
                        <img src="https://media-exp1.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAP9AAAAJDU5M2Y4N2RlLTQxZmYtNDhhYy04ODA0LWVmMjg0NzMwMGRmNg.jpg" class="profile-photo-edit__preview" alt="Edit photo" height="128" width="128">
                    </button>
                </div>
            </div>
        </div>
        <div class="pv-top-card-section__body">
            <div class="pv-top-card-section__body">
                <div id="ember2909" class="pv-top-card-section__information mt3 ember-view">
                    <div class="display-flex align-items-center justify-center">
                        <h1 class="pv-top-card-section__name Sans-26px-black-85%">{{name}}</h1>
                    </div>

                    <div class="container" align="center">
                        <div class="row">
                            <div class="col-xs-6">
                                <h2 id="profile-left" class="pv-top-card-section__headline Sans-19px-black-85%">Birthday:</h2>
                            </div>
                            <div class="col-xs-6">
                                <h2 style="text-align: left" class="pv-top-card-section__headline Sans-19px-black-85%" Style="text-align:left; padding-left:25%;">{{birthday}}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h2 id="profile-left" class="pv-top-card-section__headline Sans-19px-black-85%">Gender:</h2>
                            </div>
                            <div class="col-xs-6">
                                <h2 style="text-align: left" class="pv-top-card-section__headline Sans-19px-black-85%" Style="text-align:left; padding-left:25%;">{{gender}}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h2 id="profile-left" class="pv-top-card-section__headline Sans-19px-black-85%">Expertise:</h2>
                            </div>
                            <div class="col-xs-6">
                                <h2 style="text-align: left" class="pv-top-card-section__headline Sans-19px-black-85%" Style="text-align:left; padding-left:25%;">{{expertise}}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h2 id="profile-left" class="pv-top-card-section__headline Sans-19px-black-85%">Description:</h2>
                            </div>
                            <div class="col-xs-6">
                                <h2 style="text-align: left" class="pv-top-card-section__headline Sans-19px-black-85%" Style="text-align:left; padding-left:25%;">{{description}}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h2 id="profile-left" class="pv-top-card-section__headline Sans-19px-black-85%">E-mail:</h2>
                            </div>
                            <div class="col-xs-6">
                                <h2 style="text-align: left" class="pv-top-card-section__headline Sans-19px-black-85%" Style="text-align:left; padding-left:25%;">{{email}}</h2>
                            </div>
                        </div>
                    </div>

                <div id="ember2914" class="pv-top-card-section__summary ember-view"><!----></div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

app_stats/templates/app_stats/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ling In</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/stats.css' %}" />
</head>

<body style="background-color:#f7faff;">
    <header>
        {% include "app_stats/partials/header.html" %}
    </header>
    <content>
        <div class="container" style="margin-top: 100px">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer>
        {% include "app_stats/partials/footer.html" %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</body>
</html>

app_stats/templates/app_stats/partials/footer.html
<div class="footer-nowhitespace">
    <h4 style="text-align: center;">Made by Para Pengabdi Beskem</h4>
    <p style="text-align: center;">Copyleft (ɔ) 2017</p>
</div>

app_stats/templates/app_stats/partials/header.html
{% load static %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img alt="logo" class="title-nav" src="{% static 'img/nav-icon.png' %}" width="100px" height="30px"></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li id="status"><a href="/status/">Status</a></li>
                <li id="profile"><a href="/profile/">Profile</a></li>
                <li id="add-friend"><a href="/add-friend/">Friends</a></li>
                <li id="stats" class="active"><a href="/stats/">Stats</a></li>
            </ul>
        </div>
    </div>
</nav>

<script>
    $('a').parents('li,ul').removeClass('active');
    $('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');
</script>

app_stats/templates/app_stats/stats.html
{% extends "app_stats/layout/base.html" %}

{% block content %}
<h2 style="margin-top: -20px">Statistics</h2>
<hr>
<div id="ember2844" class="Elevation-2dp profile-background-image profile-background-image--loading ember-view">
</div>
<div id="ember2853" class="ember-view">
    <section id="ember2858" class="pv-profile-section pv-top-card-section artdeco-container-card ember-view">
        <div class="pv-top-card-section__profile-photo-container">
            <div class="pv-top-card-section__photo-wrapper EntityPhoto-circle-8">
                <label for="member-photo-edit-upload-input" class="visually-hidden">
                    "Profile photo"
                </label>
                <div class="pv-top-card-section__edit-photo profile-photo-edit ember-view">
                    <button data-control-name="edit_profile_photo" class="profile-photo-edit__edit-btn" data-ember-action data-ember-action-2888="2888">
                        <img src="https://media-exp1.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAP9AAAAJDU5M2Y4N2RlLTQxZmYtNDhhYy04ODA0LWVmMjg0NzMwMGRmNg.jpg" class="profile-photo-edit__preview" alt="Edit photo" height="128" width="128">
                    </button>
                </div>
            </div>
        </div>
        <div class="pv-top-card-section__body">
            <div class="pv-top-card-section__body">
                <div id="ember2909" class="pv-top-card-section__information mt3 ember-view">
                    <div class="display-flex align-items-center justify-center">
                        <h1 class="pv-top-card-section__name Sans-26px-black-85%">{{name}}</h1>
                    </div>
                    <!--Friends and Post-->
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-xs-6">
                                    <h2 id="text-left" class="pv-top-card-section__headline Sans-19px-black-85%">Friends: {{number_of_friends}}</h2>
                                </div>
                                <div class="col-xs-6">
                                    <h2 id="text-right" class="pv-top-card-section__headline Sans-19px-black-85%">Posts: {{number_of_posts}}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--Latest post title-->
                    <div class="row">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-xs-6">
                                    <h2 id="text-left" class="pv-top-card-section__headline Sans-19px-black-85%">Latest Post:</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--Latest post-->
                    <div class="row" style="margin-top: 5px">
                        <div class="col-sm-4"></div>
                            <div class="col-sm-4" style="background-color:#edf3ff; padding-top: 5px; padding-bottom: 5px">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="pv-top-card-section__school  Sans-17px-black-70% mb1 inline">{{latest}}</h3>
                                    </div>
                                </div>
                                <div class="row" style="text-align:left; padding-top:5px">
                                    <div class="col-sm-12">
                                        <h3 class="pv-top-card-section__school  Sans-13px-black-60% mb1 inline" style="text-align:left">{{latest.created_date}}</h3>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="ember2914" class="pv-top-card-section__summary ember-view"><!----></div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

app_status/templates/app_status/status.html
{% extends "app_stats/layout/base.html" %}

{% block content %}

<h2>Status</h2>
<hr>
<section name="form">
    <form id="form" method="POST" action="{% url 'app-status:update_status' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="update" class="btn btn-default">Update</button>
    </form>
</section>
<hr>
<section name="post" id="post">
    <div class="container">
        <h2 class="post-title">Posts</h2>
        <div class="flex">
            {% if message %}
                {% for data in message reversed%}
                    <div class="flex-item">
                        <div class="show-post">
                            <div class="show-post-message">
                                <h4>Para Pengabdi Beskem</h4>
                            </div>
							<div class="show-post-message">
                                {{data.message}}
                            </div>
                            <div class="show-post-date-added">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> There are no data.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}